/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesMeoRouteImport } from './routes/services.meo'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesWebRenewalRouteImport } from './routes/services.web-renewal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMeoRoute = ServicesMeoRouteImport.update({
  id: '/services/meo',
  path: '/services/meo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRenewalRoute = ServicesWebRenewalRouteImport.update({
  id: '/services/web-renewal',
  path: '/services/web-renewal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/meo': typeof ServicesMeoRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-renewal': typeof ServicesWebRenewalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/meo': typeof ServicesMeoRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-renewal': typeof ServicesWebRenewalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/meo': typeof ServicesMeoRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-renewal': typeof ServicesWebRenewalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services/meo' | '/services/seo' | '/services/web-renewal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services/meo' | '/services/seo' | '/services/web-renewal'
  id:
    | '__root__'
    | '/'
    | '/services/meo'
    | '/services/seo'
    | '/services/web-renewal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesMeoRoute: typeof ServicesMeoRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebRenewalRoute: typeof ServicesWebRenewalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/meo': {
      id: '/services/meo'
      path: '/services/meo'
      fullPath: '/services/meo'
      preLoaderRoute: typeof ServicesMeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-renewal': {
      id: '/services/web-renewal'
      path: '/services/web-renewal'
      fullPath: '/services/web-renewal'
      preLoaderRoute: typeof ServicesWebRenewalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesMeoRoute: ServicesMeoRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebRenewalRoute: ServicesWebRenewalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
